<template>
  <div id="cuadro-menu">
    <a :href="enlace.link">
      <div :id="cuadro.nombre" :style="cuadro.tamagno" class="cuadro cuadro.nombre">
        <p class="texto">{{ cuadro.texto }}</p>
      </div>
    </a>
  </div>
</template>

<script>
  export default {
    name: 'cuadro-menu',
    props: {
        enlace: Object,
        cuadro: Object,
    },
  }
</script>
  
<style scoped>
  .texto {
    visibility: hidden;
  }

  .cuadro {
    display: flex;
    justify-content: center;
    align-items: center;
    /* animation: wobble-hor-bottom 15s infinite both; */
  }

  /* .navbar1 {
    animation: wobble-hor-bottom 15s infinite both;
  } */

  .cuadro:hover {
    visibility: hidden;
  }

  .cuadro:hover .texto {
    visibility: visible;
    font-size: 1rem;
    color: black;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-6-27 3:16:9
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation wobble-hor-bottom
  * ----------------------------------------
  */

  @keyframes wobble-hor-bottom {
    0%,
    100% {
      transform: translateX(0%);
      transform-origin: 50% 50%;
    }
    15% {
      transform: translateX(-30px) rotate(-6deg);
    }
    30% {
      transform: translateX(15px) rotate(6deg);
    }
    45% {
      transform: translateX(-15px) rotate(-3.6deg);
    }
    60% {
      transform: translateX(9px) rotate(2.4deg);
    }
    75% {
      transform: translateX(-6px) rotate(-1.2deg);
    }
  }

</style>