<template>
  <div id="menu">
    <div v-for="opcion in opciones" :key="opcion.id">
      <CuadroMenu :enlace=opcion.enlace :cuadro=opcion.cuadro /> 
    </div>
  </div>
</template>

<script>
  import CuadroMenu from '@/components/CuadroMenu.vue';
  import paramMenu from "@/assets/language/ES/ES-paramMenu.json";

  export default {
    name: 'menu',
    components: {
      CuadroMenu,
    },
    data() {
      return {
        opciones: paramMenu,
      }
    },
  }
</script>

<style scoped>

  /* ----------------------------------------------
  * Generated by Animista on 2021-6-27 3:16:9
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation wobble-hor-bottom
  * ----------------------------------------
  */
  /* #navbar1 {
    animation: wobble-hor-bottom 15s infinite both;
  }

  #navbar2 {
    animation: wobble-hor-bottom 5s infinite both;
  }

  @keyframes wobble-hor-bottom {
    0%,
    100% {
      transform: translateX(0%);
      transform-origin: 50% 50%;
    }
    15% {
      transform: translateX(-30px) rotate(-6deg);
    }
    30% {
      transform: translateX(15px) rotate(6deg);
    }
    45% {
      transform: translateX(-15px) rotate(-3.6deg);
    }
    60% {
      transform: translateX(9px) rotate(2.4deg);
    }
    75% {
      transform: translateX(-6px) rotate(-1.2deg);
    }
  } */

</style>